 export const resObj = [
    {
      id: 1,
      name: "KFC",
      costForTwo: 30000,
      cuisines: ["Burger", "Biriyani", "Snacks", "Fast Food"],
      delivayTime: 5,
    },
    {
      id: 2,
      name: "McDonald's",
      costForTwo: 25000,
      cuisines: ["Burger", "French Fries", "Fast Food"],
      delivayTime: 4,
    },
    {
      id: 3,
      name: "ABc's",
      costForTwo: 25000,
      cuisines: ["Burger", "French Fries", "Fast Food"],
      delivayTime: 4,
    },
    {
      id: 4,
      name: "XYZ's",
      costForTwo: 25000,
      cuisines: ["Tea", "Rice Fries", "  Food"],
      delivayTime: 4,
    },
    {
      id: 5,
      name: "PQR's",
      costForTwo: 25000,
      cuisines: ["Rooti   ", "Rice ", "Chines Food"],
      delivayTime: 14,
    },
    {
      id: 6,
      name: "Ddaasghsd's",
      costForTwo: 28000,
      cuisines: ["pitha", " kbddd", "Fast Food"],
      delivayTime: 4,
    },
    {
      id: 7,
      name: "McDonald's",
      costForTwo: 25000,
      cuisines: ["Burger", "French Fries", "Fast Food"],
      delivayTime: 4,
    },
    {
      id: 8,
      name: "McDonald's",
      costForTwo: 25000,
      cuisines: ["Burger", "French Fries", "Fast Food"],
      delivayTime: 4,
    },
    {
      id: 9,
      name: "McDonald's",
      costForTwo: 25000,
      cuisines: ["Burger", "French Fries", "Fast Food"],
      delivayTime: 4,
    },
    {
      id: 45,
      name: "McDonald's",
      costForTwo: 25000,
      cuisines: ["Burger", "French Fries", "Fast Food"],
      delivayTime: 4,
    },
    {
      id: 67,
      name: "McDonald's",
      costForTwo: 25000,
      cuisines: ["Burger", "French Fries", "Fast Food"],
      delivayTime: 4,
    },
    {
      id: 86,
      name: "McDonald's",
      costForTwo: 25000,
      cuisines: ["Burger", "French Fries", "Fast Food"],
      delivayTime: 4,
    },
  ];